### ISSUE TITLE
Open copied file on external app

### ISSUE THREAD

**Issue by pushingpop** [alpha0010/react-native-file-access#49]
**Feature**
Is there a way to get (dir: 'audio' | 'downloads' | 'images' | 'video') path?

**Motivation**
I need to move the file to images path, then open this image. If possible add an uri response from cpExternal, or expose this as a Directory constants.

**Comment by alpha0010** [comment]
Difficult to decide how to do so properly, especially since system security prevents read/write on arbitrary locations (except if device is rooted).  I can return the path:
- On iOS, path is retrieved from `NSSearchPathForDirectoriesInDomains()`, which tends to be located within the app's own sandbox.
- On Android, files are sent to `MediaStore`. App gets a `content://` uri during the process. Uncertain if this uri is valid between apps.

Android and iOS both have various ways to share data between apps, especially when both apps can coordinate.  I would prefer avoiding adding too much native code, if it is not actually of use.

How are you handling communication between apps?  Is there a specific native API that would be useful to have access to via this library?

**Comment by alpha0010** [comment]
Inactive, closing.  Please open a new issue with further details, if you are still interested.
